name: my-env
channels:
  - conda-forge
dependencies:
  - xeus-cling=0.7.1
  - xtensor=0.20.8
  - xtensor-blas=0.16.1
  - notebook
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
